version: '3.9'

services:
  api:
    container_name: reunion-social-media-api
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - "database"
    env_file: './.env'
    restart: always
    command: sh -c "npm run db-migrate && npm run start"

  database:
    image: postgres
    environment:
      - POSTGRES_USER=reunion
      - POSTGRES_DB=reunion
      - POSTGRES_PASSWORD=reunion
    volumes:
      - dev-postgres-data:/var/lib/postressql/data 
    ports:
      - "5432:5432"
    restart: always
    
  
volumes:
  dev-postgres-data:
