version: '3.9'

services:
  postgres:
    container_name: reunion-postgres
    image: postgres
    environment:
      - POSTGRES_USER=reunion
      - POSTGRES_DB=reunion
      - POSTGRES_PASSWORD=reunion
    volumes:
      - dev-postgres-data:/var/lib/postressql/data 
    ports:
      - "5431:5432"
  
volumes:
  dev-postgres-data:
